// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOF-Zbi9MFLmmW5SjXLVoew-SEj6cnfx4',
    appId: '1:550018273495:web:8fd609f056acc10905a092',
    messagingSenderId: '550018273495',
    projectId: 'slowdown-app-c2d1c',
    authDomain: 'slowdown-app-c2d1c.firebaseapp.com',
    storageBucket: 'slowdown-app-c2d1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm8VojLJPh97Pjk5TqWm7xDo6J3x5rFtY',
    appId: '1:550018273495:android:d06bc0665b79f64505a092',
    messagingSenderId: '550018273495',
    projectId: 'slowdown-app-c2d1c',
    storageBucket: 'slowdown-app-c2d1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnE1nBPICbzFfHdhEFYC0aLieB2vCQ094',
    appId: '1:550018273495:ios:51dbd7b66251352005a092',
    messagingSenderId: '550018273495',
    projectId: 'slowdown-app-c2d1c',
    storageBucket: 'slowdown-app-c2d1c.firebasestorage.app',
    iosClientId: '550018273495-pc54fu7ci3ofkok3j032621si93bha7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.slowdown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnE1nBPICbzFfHdhEFYC0aLieB2vCQ094',
    appId: '1:550018273495:ios:51dbd7b66251352005a092',
    messagingSenderId: '550018273495',
    projectId: 'slowdown-app-c2d1c',
    storageBucket: 'slowdown-app-c2d1c.firebasestorage.app',
    iosClientId: '550018273495-pc54fu7ci3ofkok3j032621si93bha7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.slowdown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOF-Zbi9MFLmmW5SjXLVoew-SEj6cnfx4',
    appId: '1:550018273495:web:b11009cb223047ab05a092',
    messagingSenderId: '550018273495',
    projectId: 'slowdown-app-c2d1c',
    authDomain: 'slowdown-app-c2d1c.firebaseapp.com',
    storageBucket: 'slowdown-app-c2d1c.firebasestorage.app',
  );
}
